export const alphabets = [
    { char: "A", image: "/alphabets/A.jpg" },
    { char: "B", image: "/alphabets/B.jpg" },
    { char: "C", image: "/alphabets/C.jpg" },
    { char: "D", image: "/alphabets/D.jpg" },
    { char: "E", image: "/alphabets/E.jpg" },
    { char: "F", image: "/alphabets/F.jpg" },
    { char: "G", image: "/alphabets/G.jpg" },
    { char: "H", image: "/alphabets/H.jpg" },
    { char: "I", image: "/alphabets/I.jpg" },
    { char: "J", image: "/alphabets/J.jpg" },
    { char: "K", image: "/alphabets/K.jpg" },
    { char: "L", image: "/alphabets/L.jpg" },
    { char: "M", image: "/alphabets/M.jpg" },
    { char: "N", image: "/alphabets/N.jpg" },
    { char: "O", image: "/alphabets/O.jpg" },
    { char: "P", image: "/alphabets/P.jpg" },
    { char: "Q", image: "/alphabets/Q.jpg" },
    { char: "R", image: "/alphabets/R.jpg" },
    { char: "S", image: "/alphabets/S.jpg" },
    { char: "T", image: "/alphabets/T.jpg" },
    { char: "U", image: "/alphabets/U.jpg" },
    { char: "V", image: "/alphabets/V.jpg" },
    { char: "W", image: "/alphabets/W.jpg" },
    { char: "X", image: "/alphabets/X.jpg" },
    { char: "Y", image: "/alphabets/Y.jpg" },
    { char: "Z", image: "/alphabets/Z.jpg" },
];

export const words = [
    { word: 'Hello', hindi: 'नमस्ते', image: '/words/Hello.webp' },
    { word: 'Thank You', hindi: 'धन्यवाद', image: '/words/ThankYou.webp' },
    { word: 'Yes', hindi: 'हाँ', image: '/words/Yes.webp' },
    { word: 'No', hindi: 'नहीं', image: '/words/No.webp' },
    { word: 'Please', hindi: 'कृपया', image: '/words/Please.webp' },
    { word: 'Sorry', hindi: 'क्षमा करें', image: '/words/Sorry.webp' },
    { word: 'Help', hindi: 'मदद', image: '/words/Help.webp' },
    { word: 'Love', hindi: 'प्रेम', image: '/words/Love.webp' },
];